### ISSUE TITLE
jdeps --multi-release

### ISSUE THREAD

**Issue by rashaverak** [moditect/moditect-gradle-plugin#9] opened 2019-03-28 13:21 UTC
Hello, do you have any ETA to make this plugin usable for the unlucky of us ?

**Comment by siordache** [comment] 2019-03-29 15:03
Java 12 fixed [the multi-release bug](https://bugs.openjdk.java.net/browse/JDK-8210502).
Did you try running Gradle with Java 12?

**Comment by rashaverak** [comment] 2019-04-01 07:55
Java 12 does not help

> Task :generateModuleInfo FAILED
Error: jaxb-api-2.3.1.jar is a multi-release jar file but --multi-release option is not set

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateModuleInfo'.
> Invocation of jdeps failed: jdeps --generate-module-info /home/lukas/projects/xx/build/moditect --add-modules javafx.swing,javafx.web,javafx.fxml,javafx.controls,javafx.media,javafx.graphics,javafx.base,ui,vboxjxpcom,org.apache.commons.lang3,commons.validator,semver4j,java.uuid.generator,org.slf4j.jul,io.sentry,org.slf4j,org.apache.httpcomponents.httpcore,selenium.server,com.fasterxml.jackson.databind,com.fasterxml.jackson.annotation,com.fasterxml.jackson.dataformat.yaml,vboxjws,junit,org.apache.commons.codec,annotations,java.xml.ws,commons.beanutils,commons.collections,commons.digester,selenium.java,selenium.chrome.driver,selenium.edge.driver,selenium.firefox.driver,selenium.ie.driver,selenium.opera.driver,selenium.safari.driver,selenium.support,selenium.remote.driver,selenium.api,jcommander,net.bytebuddy,commons.exec,com.google.common,jcip.annotations,okhttp3,okio,javax.servlet.api,snakeyaml,com.fasterxml.jackson.core,hamcrest.core,java.xml.bind,java.xml.soap,java.annotation,checker.compat.qual,error.prone.annotations,j2objc.annotations,animal.sniffer.annotations,java.activation --module-path /home/lukas/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-swing/11.0.2/cb57db3e5bd1e2b62b17c8a504858bfc26fa54b1/javafx-swing-11.0.2-linux.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-web/11.0.2/49ca03e2fd58cbb0ad94f6a6bd11e0c043e541a7/javafx-web-11.0.2-linux.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-fxml/11.0.2/1b8a331d5f393b48de0aef59b3c967a312967290/javafx-fxml-11.0.2-linux.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-controls/11.0.2/5f6929050a744aab39ebfc1e8e5dd03bcd2ad47b/javafx-controls-11.0.2-linux.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-media/11.0.2/8bc5daaa19f2ff103cd85f751ad021eb71ba7db7/javafx-media-11.0.2-linux.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-graphics/11.0.2/ef4c34f0ca77cd99100b76c2ccf1dce383572bb1/javafx-graphics-11.0.2-linux.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-base/11.0.2/8db178adb1085d455e5ef643a48c34959c8771c1/javafx-base-11.0.2-linux.jar:/home/lukas/projects/xx/lib/ui.jar:/home/lukas/projects/xx/lib/vboxjxpcom.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.8.1/6505a72a097d9270f7a9e7bf42c4238283247755/commons-lang3-3.8.1.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/commons-validator/commons-validator/1.6/e989d1e87cdd60575df0765ed5bac65c905d7908/commons-validator-1.6.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/com.vdurmont/semver4j/2.2.0/2846945cb3bd65b65abf49a809f6cb907bbdb745/semver4j-2.2.0.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/com.fasterxml.uuid/java-uuid-generator/3.1.5/8784df945176ab4e8e268fd24508cf882d3378de/java-uuid-generator-3.1.5.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-jdk14/1.8.0-beta4/f87385b75367c3bf35c546b13b80b333731daa9e/slf4j-jdk14-1.8.0-beta4.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/io.sentry/sentry/1.7.21/830b5214d178189de482443aa20919697079edfd/sentry-1.7.21.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.8.0-beta4/83b0359d847ee053d745be7ec0d8e9e8a44304b4/slf4j-api-1.8.0-beta4.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.4.11/de748cf874e4e193b42eceea9fe5574fabb9d4df/httpcore-4.4.11.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-server/3.141.59/970059131887e04ede14b433a7a505a793585bce/selenium-server-3.141.59.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.9.8/11283f21cc480aa86c4df7a0a3243ec508372ed2/jackson-databind-2.9.8.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.9.8/ba7f0e6f8f1b28d251eeff2a5604bed34c53ff35/jackson-annotations-2.9.8.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/2.9.8/a1c807329eb0c75976aeb5961a506b3516ffeae3/jackson-dataformat-yaml-2.9.8.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.virtualbox/vboxjws/4.1.4/fb2e68b0cedf431562a76b5791f2fd26c501fa84/vboxjws-4.1.4.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/junit/junit/4.11/4e031bb61df09069aeb2bffb4019e7a5034a4ee0/junit-4.11.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.12/47a28ef1ed31eb182b44e15d49300dee5fadcf6a/commons-codec-1.12.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/16.0.2/dab5655eb9abe23f2245c34e66c9813c7daf4563/annotations-16.0.2.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/javax.xml.ws/jaxws-api/2.3.1/15e46dba25b1f767a3f517721badf6cce8dbb13d/jaxws-api-2.3.1.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/commons-beanutils/commons-beanutils/1.9.2/7a87d845ad3a155297e8f67d9008f4c1e5656b71/commons-beanutils-1.9.2.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/commons-collections/commons-collections/3.2.2/8ad72fe39fa8c91eaaf12aadb21e0c3661fe26d5/commons-collections-3.2.2.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/commons-digester/commons-digester/1.8.1/3dec9b9c7ea9342d4dbe8c38560080d85b44a015/commons-digester-1.8.1.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-java/3.141.59/e8e20b741299cb8ffedbd2925a3ab69d08b41063/selenium-java-3.141.59.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-chrome-driver/3.141.59/67137314736c6a2f39a8aa59a562e9616ae5f77e/selenium-chrome-driver-3.141.59.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-edge-driver/3.141.59/fc09c66f2d0b33b0816d770761ad1d599ef0df29/selenium-edge-driver-3.141.59.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-firefox-driver/3.141.59/a99f2fe2a42747ed9809d4f62f51a9e1b336dde8/selenium-firefox-driver-3.141.59.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-ie-driver/3.141.59/677b9b414a3a9bb2aeea89042a7b326edeb13a82/selenium-ie-driver-3.141.59.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-opera-driver/3.141.59/6b11ed01182bfd8bb62ddeae34cf9eadd3cfc7ff/selenium-opera-driver-3.141.59.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-safari-driver/3.141.59/a32b5b88f46ea4b0356079f0d2e2217543923046/selenium-safari-driver-3.141.59.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-support/3.141.59/8735de5049acf0e761defc65ee5837d6541abaf5/selenium-support-3.141.59.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-remote-driver/3.141.59/1c79ca890c312ff9916bd95df4f0c5182ec722d8/selenium-remote-driver-3.141.59.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-api/3.141.59/e006ffd3aa7841e6e9125d9e6691b3a6b7592b05/selenium-api-3.141.59.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/com.beust/jcommander/1.72/6375e521c1e11d6563d4f25a07ce124ccf8cd171/jcommander-1.72.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.8.15/cb36fe3c70ead5fcd016856a7efff908402d86b8/byte-buddy-1.8.15.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-exec/1.3/8dfb9facd0830a27b1b5f29f84593f0aeee7773b/commons-exec-1.3.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/25.0-jre/7319c34fa5866a85b6bad445adad69d402323129/guava-25.0-jre.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/net.jcip/jcip-annotations/1.0/afba4942caaeaf46aab0b976afd57cc7c181467e/jcip-annotations-1.0.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/okhttp/3.11.0/75966e05a49046ca2ae734e5626f28837a8d1e82/okhttp-3.11.0.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/com.squareup.okio/okio/1.14.0/102d7be47241d781ef95f1581d414b0943053130/okio-1.14.0.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/javax.servlet/javax.servlet-api/3.1.0/3cd63d075497751784b2fa84be59432f4905bf7c/javax.servlet-api-3.1.0.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.23/ec62d74fe50689c28c0ff5b35d3aebcaa8b5be68/snakeyaml-1.23.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.9.8/f5a654e4675769c716e5b387830d19b501ca191/jackson-core-2.9.8.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/javax.xml.bind/jaxb-api/2.3.1/8531ad5ac454cc2deb9d4d32c40c4d7451939b5d/jaxb-api-2.3.1.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/javax.xml.soap/javax.xml.soap-api/1.4.0/667ef2eee594ca7e05a1cbe0b37a428f7b57778f/javax.xml.soap-api-1.4.0.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/javax.annotation/javax.annotation-api/1.3.2/934c04d3cfef185a8008e7bf34331b79730a9d43/javax.annotation-api-1.3.2.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.checkerframework/checker-compat-qual/2.0.0/fc89b03860d11d6213d0154a62bcd1c2f69b9efa/checker-compat-qual-2.0.0.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.1.3/39b109f2cd352b2d71b52a3b5a1a9850e1dc304b/error_prone_annotations-2.1.3.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/com.google.j2objc/j2objc-annotations/1.1/ed28ded51a8b1c6b112568def5f4b455e6809019/j2objc-annotations-1.1.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/org.codehaus.mojo/animal-sniffer-annotations/1.14/775b7e22fb10026eed3f86e8dc556dfafe35f2d5/animal-sniffer-annotations-1.14.jar:/home/lukas/.gradle/caches/modules-2/files-2.1/javax.activation/javax.activation-api/1.2.0/85262acf3ca9816f9537ca47d5adeabaead7cb16/javax.activation-api-1.2.0.jar -q /home/lukas/.gradle/caches/modules-2/files-2.1/commons-beanutils/commons-beanutils/1.9.2/7a87d845ad3a155297e8f67d9008f4c1e5656b71/commons-beanutils-1.9.2.jar

**Comment by siordache** [comment] 2019-04-02 11:26
You're right, Java 12 doesn't help. The error is caused by [this issue](https://github.com/moditect/moditect/issues/70), which will be fixed in the next ModiTect release.

**Comment by siordache** [comment] 2019-04-06 07:18
@rashaverak Try inserting the following into your `generateModuleInfo`, `addMainModuleInfo`, and `addDependenciesModuleInfo` blocks:
```
jdepsExtraArgs = ['--multi-release', '9']
```

A similar workaround has been successfully applied to [this project](https://github.com/moditect/moditect/issues/59#issuecomment-480272324). Java 12 is still needed.

**Comment by siordache** [comment] 2020-03-24 10:05
Fixed in 1.0.0-rc1.

**Closed as completed by siordache** 2020-03-24 10:05 UTC
